sudo: false
language: python

script:
  - tox

install:
  - pip install tox

matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36-django30
    - python: "3.7"
      env: TOXENV=py37-django22
    - python: "3.7"
      env: TOXENV=py37-django30

    # Linting
    - python: "3.7"
      env: TOXENV=lint

notifications:
  email: false
  irc: "irc.freenode.org#xelnext"
