sudo: false
language: python

script:
  - tox

install:
  - pip install tox

matrix:
  include:
    - python: "3.5"
      env: TOXENV=py35-django111
    - python: "3.6"
      env: TOXENV=py36-django22
    - python: "3.7"
      env: TOXENV=py37-django111
      env: TOXENV=py37-django22

    # Linting
    - python: "3.7"
      env: TOXENV=lint

notifications:
  email: false
  irc: "irc.freenode.org#xelnext"
